version: '3.9'

services:

  # MySQL Service
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    volumes:
      - mysql_volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=dockerxlaravel
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin123
    ports:
      - "3307:3306"
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 3
      timeout: 5s

  # PHP-FPM Service (Laravel)
    # PHP-FPM Service (Laravel)
  php:
    container_name: php
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - "D:/Laravel/Laravel:/var/www/html"   # Mount project Laravel ke container
    networks:
      - app_network
    depends_on:
      - mysql

  # NGINX Service
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    volumes:
      - "D:/Laravel/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "D:/Laravel/Laravel:/var/www/html"  # Mount project Laravel
    ports:
      - "8080:80"
    networks:
      - app_network
    depends_on:
      - php
  
  # phpMyAdmin Service
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8081:80"  # Akses phpMyAdmin di port 8081
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=123456
    depends_on:
      - mysql
    networks:
      - app_network


volumes:
  mysql_volume:

networks:
  app_network:
    driver: bridge
